//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package PhysicsGame.MapClasses {
		import org.flixel.*;
	import org.overrides.*;

	
	public class MapTestLevel extends MapBase {
		//Media content declarations
		[Embed(source="../../data/Maps/MapCSV_TestLevel_LayerMain.txt", mimeType="application/octet-stream")] public var CSV_Main:Class;
		[Embed(source="../../data/tiles_all.png")] public var Img_Main:Class;

		
		public function MapTestLevel() {

			_setCustomValues();

			bgColor = 0xffffffff;

			layerMain = new ExTilemap();
			layerMain.loadMap(new CSV_Main, Img_Main);

			allLayers = [ layerMain ];

			mainLayer = layerMain;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 1600;
			boundsMaxY = 320;
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
