//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package com.adamatomic.Mode {
	import com.adamatomic.flixel.*;
	
	public class MapTestLevel extends MapBase {
		//Media content declarations
		[Embed(source="../../../data/Maps/MapCSV_TestLevel_LayerMain.txt", mimeType="application/octet-stream")] public var CSV_LayerMain:Class;
		[Embed(source="../../../data/tiles_all.png")] public var Img_LayerMain:Class;

		
		public function MapTestLevel() {

			_setCustomValues();

			bgColor = 0xffffffff;

			layerMain = new FlxTilemap(new CSV_LayerMain, Img_LayerMain,3,0);
			layerMain.x = 0;
			layerMain.y = 0;
			layerMain.scrollFactor.x = 1.000000;
			layerMain.scrollFactor.y = 1.000000;

			allLayers = [ layerMain ];

			mainLayer = layerMain;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 1600;
			boundsMaxY = 320;
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
